### ISSUE TITLE
launch with substitution args cannot work

### ISSUE THREAD

**Issue by guihomework** [kuka-isir/ati_sensor#1]
Suggested command 
`roslaunch ati_sensor ft_sensor.launch ip:=192.168.10.100`
fails
`Invalid <arg> tag: cannot override arg 'ip', which has already been set.`

due to wrong arg setting in launch files
Should be

```
  <arg name="ip" default="192.168.100.103"/>
  <arg name="frame" default="/ati_link"/>
```

**Comment by ahoarau** [comment]
Indeed. Thanks
