### ISSUE TITLE
add gauge bias setting

### ISSUE THREAD

**Issue by guihomework** [kuka-isir/ati_sensor#9]
In the web interface there is a possibility to set the gauge bias to specific values.

This was interesting to us for compensating the internal "constraints" on the gauges with no external payload attached (does not depend on sensor orientation). Once the payload was attached, we re-used the same bias setting that we entered manually to the web interface at each start.

I created a wrapper for that functionality in the sensor the same way we did the setRDTOutputRate (https://github.com/ubi-agni/ati_sensor/tree/ubi-indigo-devel) . Are you interested into such a feature, then I can create a pull request and be in sync with your branch again.

**Comment by ahoarau** [comment]
Yes I'm always on for new features :+1: 
I just added you as a developer for this repo, but if you prefer PRs, just tell me and I'll remove you from this. Happy collaborating !

**Comment by guihomework** [comment]
Will add this code soon
